CREATE TABLE PUBLIC.USER_SESSION (
  SESSION_ID CHAR(100) NOT NULL,
  SESSION_OBJECT BYTEA NOT NULL,
  EXPIRATION_DATETIME TIMESTAMP NOT NULL,
  PRIMARY KEY (SESSION_ID)
);
COMMENT ON table PUBLIC.USER_SESSION is 'ユーザセッション';
COMMENT ON column PUBLIC.USER_SESSION.SESSION_ID is 'セッションID';
COMMENT ON column PUBLIC.USER_SESSION.SESSION_OBJECT is 'セッションオブジェクト';
COMMENT ON column PUBLIC.USER_SESSION.EXPIRATION_DATETIME is '有効期限';
